# Generated by Django 5.1.7 on 2025-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('night', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
