# Generated by Django 5.1.7 on 2025-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_inventoryreport_inventory_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
